# Server configs
app:
  # Server name
  name: ${OTE_SERVER_NAME:-ote}
  # Env mode (dev or prod)
  mode: ${OTE_SERVER_MODE:-prod}
  # HTTP port
  port: ${OTE_SERVER_PORT:-8000}
  # Hostname
  hostname: ${OTE_SERVER_HOSTNAME:-127.0.0.1}
  # TLS configs
  tls:
    status: ${OTE_SERVER_TLS_STATUS:-off}
    crt_path: ${OTE_SERVER_TLS_PEMPATH:-cert/server.crt}
    key_path: ${OTE_SERVER_TLS_KEYPATH:-cert/server.key}

  # Global timeout
  timeout: ${OTE_SERVER_TIMEOUT:-50}

  # Prometheus metrics endpoint
  metrics:
    username: ${OTE_SERVER_PROM_METRICS_USERNAME:-admin}
    secret: ${OTE_SERVER_PROM_METRICS_SECRET:-secret}

  # Log configs
  log:
    # Log level, it can be debug, info, warn, error, panic, fatal
    level: ${OTE_SERVER_LOG_LEVEL:-info}
    # Output can be stdout or abs path to log file /var/logs/ote.log
    output: ${OTE_SERVER_LOG_OUTPUT:-stdout}
    # Format can be json
    format: ${OTE_SERVER_LOG_FORMAT:-json}
