# Copyright 2025 Clivern. All rights reserved.
# Use of this source code is governed by the MIT
# license that can be found in the LICENSE file.

---
ote_version: "0.1.5"
ote_download_url: "https://github.com/clivern/ote/releases/download/v{{ ote_version }}/ote_linux_x86_64.tar.gz"

ote_user: "ote"
ote_group: "ote"

ote_log_file: "/var/log/ote/ote.log"

ote_metrics_username: "admin"
ote_metrics_secret: "secret"
