---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart otel collector
  ansible.builtin.systemd:
    name: "{{ otel_collector_service_name }}"
    state: restarted

